version: "0.1.1"

services:
  api:
    build: ./api
    ports:
      - 3000:3000
    networks:
      - test
  ui:
    image: nginx:${NGINX_VERSION}-alpine
#    build: ./ui
    ports:
      - 4000:80
    volumes:
      - ./ui:/usr/share/nginx/html:ro
    depends_on:
      - api
    networks:
      - test

networks:
  test:
    driver: bridge
    attachable: true
#    attachable: false